server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
logging:
  config: classpath:logback-spring.xml

mailgun:
  key: mailgunKey